# Generated by Django 3.2.4 on 2023-09-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
