# Generated by Django 3.2.4 on 2023-09-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_closed',
        ),
    ]
